name: Build IPK

on:
  push:
    branches:
      - master
    paths:
      - 'luci-app-radmon-php7/Makefile'
      - 'luci-app-radmon-php8/Makefile'
  workflow_dispatch:

jobs:
  build:
    name: Build luci-app-radmon IPK
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”„ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ› ï¸ Set up build environment
        run: |
          echo -e "\033[34mðŸ”¨ Preparing build environment \033[0m"
          sudo -E apt-get update > /dev/null 2>&1
          sudo -E apt-get install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget > /dev/null 2>&1
          sudo -E apt-get autoremove --purge > /dev/null 2>&1
          sudo -E apt-get clean > /dev/null 2>&1

      - name: ðŸ“¦ Set up resources
        run: |
          echo -e "\033[34mðŸ—‚ï¸ Downloading SDK OpenWRT \033[0m"
          curl -s -L https://downloads.openwrt.org/releases/23.05.4/targets/x86/64/openwrt-sdk-23.05.4-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz -o sdk.tar.xz
          mkdir sdk && tar -xf sdk.tar.xz -C sdk --strip-components=1

          echo -e "\033[34mðŸ“¦ Cloning packages \033[0m"
          git clone -q https://github.com/${{ github.repository }} sdk/package/tmp
          mv sdk/package/tmp/luci-app-radmon-php7 sdk/package/
          mv sdk/package/tmp/luci-app-radmon-php8 sdk/package/
          rm -rf sdk/package/tmp

      - name: ðŸ“¡ Set up SDK feeds
        run: |
          echo -e "\033[34mðŸ” Updating SDK feeds \033[0m"
          cd sdk
          ./scripts/feeds update -a > /dev/null 2>&1

          echo -e "\033[34mðŸ”— Installing SDK feeds \033[0m"
          ./scripts/feeds install -a > /dev/null 2>&1

      - name: âš™ï¸ Configure & compile luci-app-radmon-php7
        run: |
          echo -e "\033[34mðŸ”§ Configuring SDK for luci-app-radmon-php7 \033[0m"
          cd sdk && make defconfig > /dev/null 2>&1
          rm -rf feeds/luci/contrib/package/csstidy
          sed -i '/^CONFIG_LUCI_JSMIN=/d' .config
          sed -i '/^CONFIG_LUCI_CSSTIDY=/d' .config

          echo -e "\033[34mðŸ”¨ Compiling luci-app-radmon-php7 package \033[0m"
          make package/luci-app-radmon-php7/{clean,compile} -j$(nproc) > /dev/null 2>&1

          echo -e "\033[34mðŸ“¦ Compilation completed for luci-app-radmon-php7 \033[0m"
          PKG_PATH_PHP7=$(find bin/packages/x86_64/luci/ -name 'luci-app-radmon-php7*.ipk')
          echo "PKG_PATH_PHP7=sdk/$PKG_PATH_PHP7" >> $GITHUB_ENV

      - name: âš™ï¸ Configure & compile luci-app-radmon-php8
        run: |
          echo -e "\033[34mðŸ”§ Configuring SDK for luci-app-radmon-php8 \033[0m"
          cd sdk && make defconfig > /dev/null 2>&1
          rm -rf feeds/luci/contrib/package/csstidy
          sed -i '/^CONFIG_LUCI_JSMIN=/d' .config
          sed -i '/^CONFIG_LUCI_CSSTIDY=/d' .config

          echo -e "\033[34mðŸ”¨ Compiling luci-app-radmon-php8 package \033[0m"
          make package/luci-app-radmon-php8/{clean,compile} -j$(nproc) > /dev/null 2>&1

          echo -e "\033[34mðŸ“¦ Compilation completed for luci-app-radmon-php8 \033[0m"
          PKG_PATH_PHP8=$(find bin/packages/x86_64/luci/ -name 'luci-app-radmon-php8*.ipk')
          echo "PKG_PATH_PHP8=sdk/$PKG_PATH_PHP8" >> $GITHUB_ENV

      - name: ðŸš€ Generate single release for both packages
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          name: "luci-app-radmon"
          tag_name: "v${{ github.run_number }}"
          draft: false
          prerelease: false
          files: |
            ${{ env.PKG_PATH_PHP7 }}
            ${{ env.PKG_PATH_PHP8 }}
          body: |
            ### Changelog for release v${{ github.run_number }}:

            **ðŸ“¦ New builds of luci-app-radmon packages:**
            - luci-app-radmon-php7
            - luci-app-radmon-php8
